### ISSUE TITLE
mongo connexion issue again, with issues/audit

### ISSUE THREAD

**Issue by squalou** [quantopian/PenguinDome#47]
Hi,

sorry to bother you again but I'm facing another pymongo connexion issue, similar to #44 you already solved.

This time it happens when trying to solve an issue. I'll try to solve it on my side to confirm.

```python
    main()
  File "/PenguinDome/server/issues.py", line 647, in main
    args.func(args)
  File "/PenguinDome/server/issues.py", line 507, in audit_handler
    db.issues.update(
  File "/PenguinDome/var/server-venv/lib/python3.11/site-packages/mongodb_proxy.py", line 116, in __call__
    return self.proxied_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PenguinDome/var/server-venv/lib/python3.11/site-packages/pymongo/synchronous/collection.py", line 407, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'update' method on a 'Collection' object it is failing because no such method exists.
```

kind regards

**Comment by squalou** [comment]
damn, I cannot reproduce on my test env :-)
will redeploy properly. Sorry for the noise.

**Comment by jikamens** [comment]
No, you're absolutely right, there's a bug here.

**Comment by squalou** [comment]
I was about to write back that it was probably due to my docker attempt.

For my own future memory : 
When running `bin/issues audit` from inside it seemed to work, (but I probably should have checked the logs)
but when called like this from host : `docker exec <container-id> PenguinDome/bin/issues audit` I got the issue.

Thank you once again for investigating and fixing !
