### ISSUE TITLE
question about 'stopit' dependency

### ISSUE THREAD

**Issue by squalou** [quantopian/PenguinDome#50]
Hi (again :) ),

Sorry to bother you again with questions, maybe raising issues is not the best way for these questions. Please tell if so. Thing is this project is really great and I'm about to deploy it so I'm digging in some details that need a bit of clarifications

Reading requirements.txt on client and server I've seen `git+` references for `openedx-mongodbproxy` ans `stopit`

Looks like openedx-mongodbproxy has a recent release on PyPi, could I use it ?
On the other hand stopit on PyPi dates back to 2018, even if many commits have been added since.

Is there a reason to this ?

To be honest I'd rather have versioned PyPi dependencies on requirements.txt, rather than github dependency.

thank you (again !!)

**Comment by jikamens** [comment]
PyPI MongoDBproxy release doesn't include this fix: https://github.com/openedx/MongoDBProxy/pull/28

I don't have time to figure out what to replace stopit with, and the last released version doesn't include a necessary fix: https://github.com/glenfant/stopit/pull/34

I also would prefer to be using PyPI dependencies, but my time to work on this project is limited so this is what I am able to do at this point.

**Comment by squalou** [comment]
thank you for the answer !
